### ISSUE TITLE
URL repository parsing

### ISSUE THREAD

**Issue by aseques** [cornedor/sast-report-explorer#4]
Hi, just found this viewer, I was looking exactly for this. Every thing works as announced. There's one minor thing that made it a bit more difficult to view the report.

The base url is in the format  https://gitlab.com/group/project/-/blob/main/ while the most common url that appears in gitlab is in format https://gitlab.com/group/project/-/tree/main
If the -/tree/ url could be converted to /blob/ it would make it easier to get the proper link

Thanks a lot for your work

**Comment by cornedor** [comment]
`/-/tree/` is now being replaced with `/-/blob/`, does this work correctly for your project?

**Comment by aseques** [comment]
It works great now, thanks a lot
